on: 
  push:
    branches:
      - production
name: 🚀 Deploy Procuction
jobs:
  FTP-Deploy-Action:
    name: 🎉 FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code and install dependencies
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Use Node.js 16
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16.13.1'
        cache: 'npm'

    - name: 🔨 Build Project
      run: |
        npm install
        CI=false && npm run build
    
    - name: 📂 FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        local-dir: ./build/
        server: ftp.empowernetmentoring.com
        username: publisher@empowernetmentoring.com
        password: ${{ secrets.ftp_password }}
       